spring:
    datasource:
        #schema: classpath*:scripts/schema.sql
        #continue-on-error: false
        #sql-script-encoding: utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://cdb-dgul4pxi.bj.tencentcdb.com:10023/db_mblog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: a123456!@
        type: com.alibaba.druid.pool.DruidDataSource
        #监控统计拦截的filters
        filters: stat,wall,log4j
        #druid配置
        #配置初始化大小/最小/最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        #获取连接等待超时时间
        maxWait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        timeBetweenEvictionRunsMillis: 60000
        #一个连接在池中最小生存的时间
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties:
            druid:
                stat:
                    mergeSql: true
                    slowSqlMillis: 5000
    flyway:
        enabled: true
    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.scripts.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ${site.location}/storage/indexes